# Generated by Django 4.2.3 on 2023-07-09 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_alter_item_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
